2020-11-10 19:39:48,982 INFO    MainThread:14378 [wandb_setup.py:_flush():68] setting env: {}
2020-11-10 19:39:48,982 INFO    MainThread:14378 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-11-10 19:39:48,982 INFO    MainThread:14378 [wandb_setup.py:_flush():68] setting login settings: {}
2020-11-10 19:39:48,982 INFO    MainThread:14378 [wandb_init.py:_log_setup():302] Logging user logs to /home/yunke/git/DL_MBMF/experiment/wandb/run-20201110_193948-b36dfrqw/logs/debug.log
2020-11-10 19:39:48,982 INFO    MainThread:14378 [wandb_init.py:_log_setup():303] Logging internal logs to /home/yunke/git/DL_MBMF/experiment/wandb/run-20201110_193948-b36dfrqw/logs/debug-internal.log
2020-11-10 19:39:50,024 INFO    MainThread:14378 [wandb_run.py:_console_start():1213] atexit reg
2020-11-10 19:39:50,024 INFO    MainThread:14378 [wandb_run.py:_redirect():1083] redirect: SettingsConsole.REDIRECT
2020-11-10 19:39:50,025 INFO    MainThread:14378 [wandb_run.py:_redirect():1086] Redirecting console.
2020-11-10 19:39:50,025 INFO    MainThread:14378 [redirect.py:install():204] install start
2020-11-10 19:39:50,025 INFO    MainThread:14378 [redirect.py:install():219] install stop
2020-11-10 19:39:50,025 INFO    MainThread:14378 [redirect.py:install():204] install start
2020-11-10 19:39:50,026 INFO    MainThread:14378 [redirect.py:install():219] install stop
2020-11-10 19:39:50,026 INFO    MainThread:14378 [wandb_run.py:_redirect():1130] Redirects installed.
2020-11-10 19:39:50,026 INFO    MainThread:14378 [wandb_config.py:__setitem__():135] config set more = custom - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f53972545c0>>
2020-11-10 19:39:50,026 INFO    MainThread:14378 [wandb_run.py:_config_callback():545] config_cb more custom {'_wandb': {'cli_version': '0.10.10', 'python_version': '3.6.9', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}, 'more': 'custom'}
2020-11-10 19:43:54,291 INFO    MainThread:14378 [wandb_run.py:_atexit_cleanup():1186] got exitcode: 255
2020-11-10 19:43:54,292 INFO    MainThread:14378 [wandb_run.py:_restore():1158] restore
2020-11-10 19:43:54,292 INFO    MainThread:14378 [redirect.py:uninstall():223] uninstall start
2020-11-10 19:43:54,292 INFO    MainThread:14378 [redirect.py:_stop():278] _stop: stdout
2020-11-10 19:43:54,293 INFO    MainThread:14378 [redirect.py:_stop():284] _stop closed: stdout
2020-11-10 19:43:54,293 INFO    stdout    :14378 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-11-10 19:43:54,293 INFO    stdout    :14378 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-11-10 19:43:54,293 INFO    MainThread:14378 [redirect.py:_stop():290] _stop joined: stdout
2020-11-10 19:43:54,293 INFO    MainThread:14378 [redirect.py:_stop():292] _stop rd closed: stdout
2020-11-10 19:43:54,293 INFO    MainThread:14378 [redirect.py:uninstall():227] uninstall done
2020-11-10 19:43:54,293 INFO    MainThread:14378 [redirect.py:uninstall():223] uninstall start
2020-11-10 19:43:54,294 INFO    MainThread:14378 [redirect.py:_stop():278] _stop: stderr
2020-11-10 19:43:54,294 INFO    stderr    :14378 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-11-10 19:43:54,294 INFO    stderr    :14378 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-11-10 19:43:54,294 INFO    MainThread:14378 [redirect.py:_stop():284] _stop closed: stderr
2020-11-10 19:43:54,294 INFO    MainThread:14378 [redirect.py:_stop():290] _stop joined: stderr
2020-11-10 19:43:54,294 INFO    MainThread:14378 [redirect.py:_stop():292] _stop rd closed: stderr
2020-11-10 19:43:54,294 INFO    MainThread:14378 [redirect.py:uninstall():227] uninstall done
2020-11-10 19:43:54,296 INFO    MainThread:14378 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "18adeff08edd4503b6755ee1a951095f"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 787
      total_bytes: 787
    }
  }
}

2020-11-10 19:43:56,308 INFO    MainThread:14378 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "5a8f802ff4f94af0a8f7823176d82bd8"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 161579
      total_bytes: 161579
    }
  }
}

2020-11-10 19:43:57,366 INFO    MainThread:14378 [wandb_run.py:_show_summary():1443] rendering summary
2020-11-10 19:43:57,366 INFO    MainThread:14378 [wandb_run.py:_show_history():1481] rendering history
2020-11-10 19:43:57,366 INFO    MainThread:14378 [wandb_run.py:_show_files():1509] logging synced files
2020-11-10 19:43:57,366 INFO    MainThread:14378 [internal.py:handle_exit():138] Internal process exited
