2020-11-18 23:28:54,734 INFO    MainThread:20612 [wandb_setup.py:_flush():68] setting env: {}
2020-11-18 23:28:54,734 INFO    MainThread:20612 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-11-18 23:28:54,734 INFO    MainThread:20612 [wandb_setup.py:_flush():68] setting login settings: {}
2020-11-18 23:28:54,734 INFO    MainThread:20612 [wandb_init.py:_log_setup():302] Logging user logs to /home/yunke/git/DL_MBMF/experiment/wandb/run-20201118_232854-15a6dm35/logs/debug.log
2020-11-18 23:28:54,734 INFO    MainThread:20612 [wandb_init.py:_log_setup():303] Logging internal logs to /home/yunke/git/DL_MBMF/experiment/wandb/run-20201118_232854-15a6dm35/logs/debug-internal.log
2020-11-18 23:28:55,636 INFO    MainThread:20612 [wandb_run.py:_console_start():1213] atexit reg
2020-11-18 23:28:55,636 INFO    MainThread:20612 [wandb_run.py:_redirect():1083] redirect: SettingsConsole.REDIRECT
2020-11-18 23:28:55,636 INFO    MainThread:20612 [wandb_run.py:_redirect():1086] Redirecting console.
2020-11-18 23:28:55,636 INFO    MainThread:20612 [redirect.py:install():204] install start
2020-11-18 23:28:55,637 INFO    MainThread:20612 [redirect.py:install():219] install stop
2020-11-18 23:28:55,637 INFO    MainThread:20612 [redirect.py:install():204] install start
2020-11-18 23:28:55,637 INFO    MainThread:20612 [redirect.py:install():219] install stop
2020-11-18 23:28:55,637 INFO    MainThread:20612 [wandb_run.py:_redirect():1130] Redirects installed.
2020-11-18 23:28:55,637 INFO    MainThread:20612 [wandb_config.py:__setitem__():135] config set more = custom - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f70ec7766a0>>
2020-11-18 23:28:55,637 INFO    MainThread:20612 [wandb_run.py:_config_callback():545] config_cb more custom {'_wandb': {'cli_version': '0.10.10', 'python_version': '3.6.9', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}, 'more': 'custom'}
2020-11-18 23:31:15,003 INFO    MainThread:20612 [wandb_run.py:_atexit_cleanup():1186] got exitcode: 255
2020-11-18 23:31:15,003 INFO    MainThread:20612 [wandb_run.py:_restore():1158] restore
2020-11-18 23:31:15,004 INFO    MainThread:20612 [redirect.py:uninstall():223] uninstall start
2020-11-18 23:31:15,004 INFO    MainThread:20612 [redirect.py:_stop():278] _stop: stdout
2020-11-18 23:31:15,004 INFO    stdout    :20612 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-11-18 23:31:15,004 INFO    MainThread:20612 [redirect.py:_stop():284] _stop closed: stdout
2020-11-18 23:31:15,004 INFO    stdout    :20612 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:_stop():290] _stop joined: stdout
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:_stop():292] _stop rd closed: stdout
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:uninstall():227] uninstall done
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:uninstall():223] uninstall start
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:_stop():278] _stop: stderr
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:_stop():284] _stop closed: stderr
2020-11-18 23:31:15,005 INFO    stderr    :20612 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-11-18 23:31:15,005 INFO    stderr    :20612 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:_stop():290] _stop joined: stderr
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:_stop():292] _stop rd closed: stderr
2020-11-18 23:31:15,005 INFO    MainThread:20612 [redirect.py:uninstall():227] uninstall done
2020-11-18 23:31:15,006 INFO    MainThread:20612 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "4b86f6db154b42d481c150a6d9e66de8"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 789
      total_bytes: 789
    }
  }
}

2020-11-18 23:31:17,009 INFO    MainThread:20612 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "90f1e0e98def4c3fbcb27e04623e3243"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 605214
      total_bytes: 605214
    }
  }
}

2020-11-18 23:31:18,098 INFO    MainThread:20612 [wandb_run.py:_show_summary():1443] rendering summary
2020-11-18 23:31:18,098 INFO    MainThread:20612 [wandb_run.py:_show_history():1481] rendering history
2020-11-18 23:31:18,098 INFO    MainThread:20612 [wandb_run.py:_show_files():1509] logging synced files
2020-11-18 23:31:18,099 INFO    MainThread:20612 [internal.py:handle_exit():138] Internal process exited
