2020-11-18 23:09:30,819 INFO    MainThread:27248 [wandb_setup.py:_flush():68] setting env: {}
2020-11-18 23:09:30,820 INFO    MainThread:27248 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-11-18 23:09:30,820 INFO    MainThread:27248 [wandb_setup.py:_flush():68] setting login settings: {}
2020-11-18 23:09:30,820 INFO    MainThread:27248 [wandb_init.py:_log_setup():302] Logging user logs to /home/yunke/git/DL_MBMF/experiment/wandb/run-20201118_230930-2k46vd30/logs/debug.log
2020-11-18 23:09:30,820 INFO    MainThread:27248 [wandb_init.py:_log_setup():303] Logging internal logs to /home/yunke/git/DL_MBMF/experiment/wandb/run-20201118_230930-2k46vd30/logs/debug-internal.log
2020-11-18 23:09:31,683 INFO    MainThread:27248 [wandb_run.py:_console_start():1213] atexit reg
2020-11-18 23:09:31,684 INFO    MainThread:27248 [wandb_run.py:_redirect():1083] redirect: SettingsConsole.REDIRECT
2020-11-18 23:09:31,684 INFO    MainThread:27248 [wandb_run.py:_redirect():1086] Redirecting console.
2020-11-18 23:09:31,684 INFO    MainThread:27248 [redirect.py:install():204] install start
2020-11-18 23:09:31,686 INFO    MainThread:27248 [redirect.py:install():219] install stop
2020-11-18 23:09:31,686 INFO    MainThread:27248 [redirect.py:install():204] install start
2020-11-18 23:09:31,686 INFO    MainThread:27248 [redirect.py:install():219] install stop
2020-11-18 23:09:31,686 INFO    MainThread:27248 [wandb_run.py:_redirect():1130] Redirects installed.
2020-11-18 23:09:31,686 INFO    MainThread:27248 [wandb_config.py:__setitem__():135] config set more = custom - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f0e0b8f15c0>>
2020-11-18 23:09:31,686 INFO    MainThread:27248 [wandb_run.py:_config_callback():545] config_cb more custom {'_wandb': {'cli_version': '0.10.10', 'python_version': '3.6.9', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}, 'more': 'custom'}
2020-11-18 23:10:06,103 INFO    MainThread:27248 [wandb_run.py:_atexit_cleanup():1186] got exitcode: 1
2020-11-18 23:10:06,104 INFO    MainThread:27248 [wandb_run.py:_restore():1158] restore
2020-11-18 23:10:06,104 INFO    MainThread:27248 [redirect.py:uninstall():223] uninstall start
2020-11-18 23:10:06,104 INFO    MainThread:27248 [redirect.py:_stop():278] _stop: stdout
2020-11-18 23:10:06,105 INFO    MainThread:27248 [redirect.py:_stop():284] _stop closed: stdout
2020-11-18 23:10:06,105 INFO    stdout    :27248 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-11-18 23:10:06,105 INFO    stdout    :27248 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-11-18 23:10:06,105 INFO    MainThread:27248 [redirect.py:_stop():290] _stop joined: stdout
2020-11-18 23:10:06,105 INFO    MainThread:27248 [redirect.py:_stop():292] _stop rd closed: stdout
2020-11-18 23:10:06,105 INFO    MainThread:27248 [redirect.py:uninstall():227] uninstall done
2020-11-18 23:10:06,105 INFO    MainThread:27248 [redirect.py:uninstall():223] uninstall start
2020-11-18 23:10:06,105 INFO    MainThread:27248 [redirect.py:_stop():278] _stop: stderr
2020-11-18 23:10:06,105 INFO    MainThread:27248 [redirect.py:_stop():284] _stop closed: stderr
2020-11-18 23:10:06,105 INFO    stderr    :27248 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-11-18 23:10:06,105 INFO    stderr    :27248 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-11-18 23:10:06,105 INFO    MainThread:27248 [redirect.py:_stop():290] _stop joined: stderr
2020-11-18 23:10:06,106 INFO    MainThread:27248 [redirect.py:_stop():292] _stop rd closed: stderr
2020-11-18 23:10:06,106 INFO    MainThread:27248 [redirect.py:uninstall():227] uninstall done
2020-11-18 23:10:06,108 INFO    MainThread:27248 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "e63632c6bc974f6f973f0b1615eecd5d"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 789
      total_bytes: 789
    }
  }
}

2020-11-18 23:10:08,111 INFO    MainThread:27248 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "16d295751852420eb60a8ba2075d745c"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 182899
      total_bytes: 182899
    }
  }
}

2020-11-18 23:10:09,189 INFO    MainThread:27248 [wandb_run.py:_show_summary():1443] rendering summary
2020-11-18 23:10:09,189 INFO    MainThread:27248 [wandb_run.py:_show_history():1481] rendering history
2020-11-18 23:10:09,190 INFO    MainThread:27248 [wandb_run.py:_show_files():1509] logging synced files
2020-11-18 23:10:09,190 INFO    MainThread:27248 [internal.py:handle_exit():138] Internal process exited
